### PR TITLE
Use image delimiter to enhance splash image.

### PR DESCRIPTION
**Pull request by gitpitch**
Hi Christophe, I came across your elm-europe-2017-talk presentation recently and really liked it. So much in fact that I plan to highlight your presentation in a new series on my blog called _GitPitch Presentation of the Day_. To give you some idea what you can expect, see the [inaugural post](https://medium.com/@gitpitch/gitpitch-presentation-of-the-day-1-db7987606d46) in this series here.

I've created this PR to make one small change to your `PITCHME.md` to better render the splash image on the second slide that shows you playing live with your band. Using an [image delimiter syntax](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#background) rather than a plain Markdown image syntax can lend _more visual punch_ for these kinds of slides.

You can see how your presentation will be rendered if your accept this PR by opening [my fork of your presentation here](https://gitpitch.com/gitpitch/elm-europe-2017-talk).

Anyway, I love what you've created here and for the purposes of adding a little punch to your presentation while demonstrating best practices it would be great if you could accept this PR before I publish my next post.

Cheers,
David

### CODE REVIEW

**Comment by cbenz** [comment]
Hi @gitpitch David!

First of all, thanks to *you* for your wonderful presentation tool! And for your kind words :smiley: I'm happy you selected my slides for the *GitPitch Presentation of the Day* (which is a very good idea by the way).

I looked at your fork, but on a wide screen, it renders like so:

gitpitch-image

Is is possible to keep the image aspect ratio?

**Comment by gitpitch** [comment]
Hi Christophe @cbenz 

Thank you very much for this feedback, it's great to hear you are enjoying using GitPitch.

Great question about preserving the image aspect ratio. In fact I just implemented and committed support for this the other day for use with slide-delimiters on a slide-by-slide basis. See the [image sizing and scaling page](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#slide-image-sizing--scaling) on the Wiki for details. 

I've just updated the PR making use of this new feature so your image is rendered with proper aspect-ratio preserved. You can see the [updated presentation here](https://gitpitch.com/gitpitch/elm-europe-2017-talk/tweak).

**Comment by cbenz** [comment]
This is awesome! I love the declarative approach of GitPitch. And that's pretty cool you talk positively about the Elm language too :)

**Comment by gitpitch** [comment]
Delighted to see this PR merged. Thanks for your help with this. And again, the great feedback. It's much appreciated.

As for Elm, I'm definitely a fan and hope to become a much bigger fan before long. I'm currently building something new using Elixir in the backend. And I hope to eventually use Phoenix and Elm in the frontend.

**Pull request merged**
